--------------------------------------------------------------------------------
-- File: DS1120_PD_volo_shim.vhd
-- Generated: 2025-10-26 17:51:07
-- Generator: tools/generate_volo_app.py
--
-- ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
-- This file is automatically generated from the VoloApp model.
-- To modify, update DS1120-PD_app.yaml and regenerate.
--
-- Description:
--   Register mapping shim for DS1120-PD VoloApp.
--   Maps raw Control Registers (CR20-CR30) to friendly signal names
--   and instantiates the application main entity.
--
-- Layer 2 of 3-Layer VoloApp Architecture:
--   Layer 1: MCC_TOP_volo_loader.vhd (static, shared)
--   Layer 2: DS1120_PD_volo_shim.vhd (THIS FILE - generated)
--   Layer 3: DS1120_PD_volo_main.vhd (hand-written app logic)
--
-- Register Mapping:

--   CR20: Armed → armed : std_logic

--   CR21: Force Fire → force_fire : std_logic

--   CR22: Reset FSM → reset_fsm : std_logic

--   CR23: Timing Control → timing_control : std_logic_vector(7 downto 0)

--   CR24: Delay Lower → delay_lower : std_logic_vector(7 downto 0)

--   CR25: Firing Duration → firing_duration : std_logic_vector(7 downto 0)

--   CR26: Cooling Duration → cooling_duration : std_logic_vector(7 downto 0)

--   CR27: Trigger Thresh High → trigger_thresh_high : std_logic_vector(7 downto 0)

--   CR28: Trigger Thresh Low → trigger_thresh_low : std_logic_vector(7 downto 0)

--   CR29: Intensity High → intensity_high : std_logic_vector(7 downto 0)

--   CR30: Intensity Low → intensity_low : std_logic_vector(7 downto 0)

--
-- References:
--   - docs/VOLO_APP_DESIGN.md
--   - DS1120-PD_app.yaml
--------------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

library WORK;
use WORK.volo_common_pkg.all;

entity DS1120_PD_volo_shim is
    port (
        ------------------------------------------------------------------------
        -- Clock and Reset
        ------------------------------------------------------------------------
        Clk         : in  std_logic;
        Reset       : in  std_logic;  -- Active-high reset

        ------------------------------------------------------------------------
        -- VOLO Control Signals (from MCC_TOP_volo_loader)
        ------------------------------------------------------------------------
        volo_ready  : in  std_logic;  -- CR0[31] - Set by loader
        user_enable : in  std_logic;  -- CR0[30] - User control
        clk_enable  : in  std_logic;  -- CR0[29] - Clock gating
        loader_done : in  std_logic;  -- BRAM loader FSM done signal

        ------------------------------------------------------------------------
        -- Application Registers (from MCC_TOP_volo_loader)
        -- Raw Control Registers CR20-CR30
        ------------------------------------------------------------------------

        app_reg_20 : in  std_logic_vector(31 downto 0);

        app_reg_21 : in  std_logic_vector(31 downto 0);

        app_reg_22 : in  std_logic_vector(31 downto 0);

        app_reg_23 : in  std_logic_vector(31 downto 0);

        app_reg_24 : in  std_logic_vector(31 downto 0);

        app_reg_25 : in  std_logic_vector(31 downto 0);

        app_reg_26 : in  std_logic_vector(31 downto 0);

        app_reg_27 : in  std_logic_vector(31 downto 0);

        app_reg_28 : in  std_logic_vector(31 downto 0);

        app_reg_29 : in  std_logic_vector(31 downto 0);

        app_reg_30 : in  std_logic_vector(31 downto 0);


        ------------------------------------------------------------------------
        -- BRAM Interface (from volo_bram_loader FSM)
        ------------------------------------------------------------------------
        bram_addr   : in  std_logic_vector(11 downto 0);  -- 4KB address space
        bram_data   : in  std_logic_vector(31 downto 0);  -- 32-bit data
        bram_we     : in  std_logic;                      -- Write enable

        ------------------------------------------------------------------------
        -- MCC I/O (from CustomWrapper)
        -- Native MCC types: signed(15 downto 0) for all ADC/DAC channels
        ------------------------------------------------------------------------
        InputA      : in  signed(15 downto 0);
        InputB      : in  signed(15 downto 0);
        OutputA     : out signed(15 downto 0);
        OutputB     : out signed(15 downto 0)
    );
end entity DS1120_PD_volo_shim;

architecture rtl of DS1120_PD_volo_shim is

    ----------------------------------------------------------------------------
    -- Friendly Signal Declarations (MCC-Agnostic Interface)
    ----------------------------------------------------------------------------

    signal armed : std_logic;  -- Arm the probe driver (one-shot operation)

    signal force_fire : std_logic;  -- Manual trigger for testing (bypasses threshold)

    signal reset_fsm : std_logic;  -- Reset state machine to READY state

    signal timing_control : std_logic_vector(7 downto 0);  -- Clock divider [7:4] and delay upper [3:0]

    signal delay_lower : std_logic_vector(7 downto 0);  -- Armed timeout delay lower 8 bits (with CR23[3:0] forms 12-bit)

    signal firing_duration : std_logic_vector(7 downto 0);  -- Number of cycles to remain in FIRING state (max 32)

    signal cooling_duration : std_logic_vector(7 downto 0);  -- Number of cycles to remain in COOLING state (min 8)

    signal trigger_thresh_high : std_logic_vector(7 downto 0);  -- Trigger voltage threshold [15:8] (2.4V = 0x3D)

    signal trigger_thresh_low : std_logic_vector(7 downto 0);  -- Trigger voltage threshold [7:0] (2.4V = 0xCF)

    signal intensity_high : std_logic_vector(7 downto 0);  -- Output intensity voltage [15:8] (clamped to 3.0V max)

    signal intensity_low : std_logic_vector(7 downto 0);  -- Output intensity voltage [7:0]


    ----------------------------------------------------------------------------
    -- Global Enable Signal
    -- Combines all VOLO_READY control bits for safe operation
    ----------------------------------------------------------------------------
    signal global_enable : std_logic;

begin

    ----------------------------------------------------------------------------
    -- Global Enable Computation
    --
    -- All 4 conditions must be met for app to operate:
    --   1. volo_ready  = 1  (loader has deployed bitstream)
    --   2. user_enable = 1  (user has enabled module)
    --   3. clk_enable  = 1  (clock gating enabled)
    --   4. loader_done = 1  (BRAM loading complete)
    ----------------------------------------------------------------------------
    global_enable <= combine_volo_ready(volo_ready, user_enable, clk_enable, loader_done);

    ----------------------------------------------------------------------------
    -- Register Mapping: Control Registers → Friendly Signals
    --
    -- Extract appropriate bit ranges from raw Control Registers
    -- based on register type (COUNTER_8BIT, PERCENT, BUTTON)
    ----------------------------------------------------------------------------

    armed <= app_reg_20(0);  -- Armed

    force_fire <= app_reg_21(0);  -- Force Fire

    reset_fsm <= app_reg_22(0);  -- Reset FSM

    timing_control <= app_reg_23(7 downto 0);  -- Timing Control

    delay_lower <= app_reg_24(7 downto 0);  -- Delay Lower

    firing_duration <= app_reg_25(7 downto 0);  -- Firing Duration

    cooling_duration <= app_reg_26(7 downto 0);  -- Cooling Duration

    trigger_thresh_high <= app_reg_27(7 downto 0);  -- Trigger Thresh High

    trigger_thresh_low <= app_reg_28(7 downto 0);  -- Trigger Thresh Low

    intensity_high <= app_reg_29(7 downto 0);  -- Intensity High

    intensity_low <= app_reg_30(7 downto 0);  -- Intensity Low


    ----------------------------------------------------------------------------
    -- Instantiate Application Main Entity
    --
    -- MCC-agnostic interface using friendly signal names only
    ----------------------------------------------------------------------------
    APP_MAIN_INST: entity WORK.DS1120_PD_volo_main
        port map (
            -- Standard Control Signals
            Clk     => Clk,
            Reset   => Reset,
            Enable  => global_enable,
            ClkEn   => clk_enable,

            -- Friendly Application Signals

            armed => armed,

            force_fire => force_fire,

            reset_fsm => reset_fsm,

            timing_control => timing_control,

            delay_lower => delay_lower,

            firing_duration => firing_duration,

            cooling_duration => cooling_duration,

            trigger_thresh_high => trigger_thresh_high,

            trigger_thresh_low => trigger_thresh_low,

            intensity_high => intensity_high,

            intensity_low => intensity_low,


            -- BRAM Interface (always exposed for consistency)
            bram_addr => bram_addr,
            bram_data => bram_data,
            bram_we   => bram_we,

            -- MCC I/O
            InputA  => InputA,
            InputB  => InputB,
            OutputA => OutputA,
            OutputB => OutputB
        );

end architecture rtl;